services:
  container:
    environment:
      MARIADB_ROOT_PASSWORD: mariasql
    ports:
      - 15000:3306
    volumes:
      - ~/mariadb:/var/lib/mariadb
    image: mariadb
    container_name: mariadb_student_db_container